//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Data
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using Newtonsoft.Json;
    
    [Serializable()]
    public class CurrencyRecord
    {
        public int ID;
        public int Desc;
        public long MaxCount;
        public string IconPath;
    }
    [Serializable()]
    public class CurrencyRecordList
    {
        public List<CurrencyRecord> rows;
        public static void LoadJson(String file, Action<CurrencyRecordList> callback = null)
        {
            AssetManager.LoadAsync<TextAsset>(file, (textAsset) =>
			{
				if (textAsset == null)
				{
					callback?.Invoke(new CurrencyRecordList());
					return;
				}
				CurrencyRecordList data = JsonConvert.DeserializeObject<CurrencyRecordList>(textAsset.text);
				callback?.Invoke(data);
			});;
        }
    }
    public class CurrencyTable
    {
        public Dictionary<System.Int32, CurrencyRecord> records = new Dictionary<System.Int32, CurrencyRecord>();
        public virtual void Init(CurrencyRecordList data)
        {
            if (null == data || null == data.rows)
				return;
			foreach (var row in data.rows)
			{
				if (!records.ContainsKey(row.ID))
					records.Add(row.ID, row);
			};
        }
        public virtual CurrencyRecord GetRecord(int key)
        {
            CurrencyRecord record;
			if (false == records.TryGetValue(key, out record))
				return null;
			return record;
        }
    }
}
