//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Data
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using Newtonsoft.Json;
    
    [Serializable()]
    public class DescRecord
    {
        public int ID;
        public string Kor;
        public string Eng;
    }
    [Serializable()]
    public class DescRecordList
    {
        public List<DescRecord> rows;
        public static void LoadJson(String file, Action<DescRecordList> callback = null)
        {
            AssetManager.LoadAsync<TextAsset>(file, (textAsset) =>
			{
				if (textAsset == null)
				{
					callback?.Invoke(new DescRecordList());
					return;
				}
				DescRecordList data = JsonConvert.DeserializeObject<DescRecordList>(textAsset.text);
				callback?.Invoke(data);
			});;
        }
    }
    public class DescTable
    {
        public Dictionary<System.Int32, DescRecord> records = new Dictionary<System.Int32, DescRecord>();
        public virtual void Init(DescRecordList data)
        {
            if (null == data || null == data.rows)
				return;
			foreach (var row in data.rows)
			{
				if (!records.ContainsKey(row.ID))
					records.Add(row.ID, row);
			};
        }
        public virtual DescRecord GetRecord(int key)
        {
            DescRecord record;
			if (false == records.TryGetValue(key, out record))
				return null;
			return record;
        }
    }
}
