//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Data
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using Newtonsoft.Json;
    
    [Serializable()]
    public class StageRecord
    {
        public int ID;
        public int Name;
        public int Description;
        public int GroupID;
        public int MaxTryCount;
        public int PlayTime;
        public int BGMID;
        public string PrefabPath;
        public int ScoreGroupID;
        public int RewardID;
        public int LimitGroupID;
        public int Order;
    }
    [Serializable()]
    public class StageRecordList
    {
        public List<StageRecord> rows;
        public static void LoadJson(String file, Action<StageRecordList> callback = null)
        {
            AssetManager.LoadAsync<TextAsset>(file, (textAsset) =>
			{
				if (textAsset == null)
				{
					callback?.Invoke(new StageRecordList());
					return;
				}
				StageRecordList data = JsonConvert.DeserializeObject<StageRecordList>(textAsset.text);
				callback?.Invoke(data);
			});;
        }
    }
    public class StageTable
    {
        public Dictionary<System.Int32, StageRecord> records = new Dictionary<System.Int32, StageRecord>();
        public virtual void Init(StageRecordList data)
        {
            if (null == data || null == data.rows)
				return;
			foreach (var row in data.rows)
			{
				if (!records.ContainsKey(row.ID))
					records.Add(row.ID, row);
			};
        }
        public virtual StageRecord GetRecord(int key)
        {
            StageRecord record;
			if (false == records.TryGetValue(key, out record))
				return null;
			return record;
        }
    }
}
