//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Data
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using Newtonsoft.Json;
    
    [Serializable()]
    public class RewardRecord
    {
        public int ID;
        public int Desc;
        public int Type;
        public int ConnectID;
        public long Value;
    }
    [Serializable()]
    public class RewardRecordList
    {
        public List<RewardRecord> rows;
        public static void LoadJson(String file, Action<RewardRecordList> callback = null)
        {
            AssetManager.LoadAsync<TextAsset>(file, (textAsset) =>
			{
				if (textAsset == null)
				{
					callback?.Invoke(new RewardRecordList());
					return;
				}
				RewardRecordList data = JsonConvert.DeserializeObject<RewardRecordList>(textAsset.text);
				callback?.Invoke(data);
			});;
        }
    }
    public class RewardTable
    {
        public Dictionary<System.Int32, RewardRecord> records = new Dictionary<System.Int32, RewardRecord>();
        public virtual void Init(RewardRecordList data)
        {
            if (null == data || null == data.rows)
				return;
			foreach (var row in data.rows)
			{
				if (!records.ContainsKey(row.ID))
					records.Add(row.ID, row);
			};
        }
        public virtual RewardRecord GetRecord(int key)
        {
            RewardRecord record;
			if (false == records.TryGetValue(key, out record))
				return null;
			return record;
        }
    }
}
