//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Data
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using Newtonsoft.Json;
    
    [Serializable()]
    public class StageScoreGroupRecord
    {
        public int ID;
        public int ScoreID1;
        public int ScoreID2;
        public int ScoreID3;
        public int ScoreValue1;
        public int ScoreValue2;
        public int ScoreValue3;
    }
    [Serializable()]
    public class StageScoreGroupRecordList
    {
        public List<StageScoreGroupRecord> rows;
        public static void LoadJson(String file, Action<StageScoreGroupRecordList> callback = null)
        {
            AssetManager.LoadAsync<TextAsset>(file, (textAsset) =>
			{
				if (textAsset == null)
				{
					callback?.Invoke(new StageScoreGroupRecordList());
					return;
				}
				StageScoreGroupRecordList data = JsonConvert.DeserializeObject<StageScoreGroupRecordList>(textAsset.text);
				callback?.Invoke(data);
			});;
        }
    }
    public class StageScoreGroupTable
    {
        public Dictionary<System.Int32, StageScoreGroupRecord> records = new Dictionary<System.Int32, StageScoreGroupRecord>();
        public virtual void Init(StageScoreGroupRecordList data)
        {
            if (null == data || null == data.rows)
				return;
			foreach (var row in data.rows)
			{
				if (!records.ContainsKey(row.ID))
					records.Add(row.ID, row);
			};
        }
        public virtual StageScoreGroupRecord GetRecord(int key)
        {
            StageScoreGroupRecord record;
			if (false == records.TryGetValue(key, out record))
				return null;
			return record;
        }
    }
}
