//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Data
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using Newtonsoft.Json;
    
    [Serializable()]
    public class StageGroupRecord
    {
        public int ID;
        public int Name;
        public int Description;
        public int RewardID;
        public int Order;
        public string ImagePath;
    }
    [Serializable()]
    public class StageGroupRecordList
    {
        public List<StageGroupRecord> rows;
        public static void LoadJson(String file, Action<StageGroupRecordList> callback = null)
        {
            AssetManager.LoadAsync<TextAsset>(file, (textAsset) =>
			{
				if (textAsset == null)
				{
					callback?.Invoke(new StageGroupRecordList());
					return;
				}
				StageGroupRecordList data = JsonConvert.DeserializeObject<StageGroupRecordList>(textAsset.text);
				callback?.Invoke(data);
			});;
        }
    }
    public class StageGroupTable
    {
        public Dictionary<System.Int32, StageGroupRecord> records = new Dictionary<System.Int32, StageGroupRecord>();
        public virtual void Init(StageGroupRecordList data)
        {
            if (null == data || null == data.rows)
				return;
			foreach (var row in data.rows)
			{
				if (!records.ContainsKey(row.ID))
					records.Add(row.ID, row);
			};
        }
        public virtual StageGroupRecord GetRecord(int key)
        {
            StageGroupRecord record;
			if (false == records.TryGetValue(key, out record))
				return null;
			return record;
        }
    }
}
