//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Data
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using Newtonsoft.Json;
    
    [Serializable()]
    public class UISoundRecord
    {
        public int ID;
        public string DevDesc;
        public string Path;
    }
    [Serializable()]
    public class UISoundRecordList
    {
        public List<UISoundRecord> rows;
        public static void LoadJson(String file, Action<UISoundRecordList> callback = null)
        {
            AssetManager.LoadAsync<TextAsset>(file, (textAsset) =>
			{
				if (textAsset == null)
				{
					callback?.Invoke(new UISoundRecordList());
					return;
				}
				UISoundRecordList data = JsonConvert.DeserializeObject<UISoundRecordList>(textAsset.text);
				callback?.Invoke(data);
			});;
        }
    }
    public class UISoundTable
    {
        public Dictionary<System.Int32, UISoundRecord> records = new Dictionary<System.Int32, UISoundRecord>();
        public virtual void Init(UISoundRecordList data)
        {
            if (null == data || null == data.rows)
				return;
			foreach (var row in data.rows)
			{
				if (!records.ContainsKey(row.ID))
					records.Add(row.ID, row);
			};
        }
        public virtual UISoundRecord GetRecord(int key)
        {
            UISoundRecord record;
			if (false == records.TryGetValue(key, out record))
				return null;
			return record;
        }
    }
}
